version: '3'
services:
  rstudio:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8787:8787"
      - "3838:3838"
    volumes:
      - ./app:/home/rstudio/app
    environment:
      - PASSWORD=rstudio